print("       ROLL WITH IT RESTAURANT")
print("-----------------------------------")
print("Customer Name: Lois")
print("-----------------------------------")
print("Food Item              Price (GHC)")
print("-----------------------------------")
print("Jollof Rice              40.00")
print("Grilled Chicken          35.00")
print("Coselaw                  10.00")
print("Coke                     15.00")  
print("-----------------------------------")
print("Total Amount            GHC 100.00")
print("-----------------------------------")
print("Thank you for dining here!")
print("Please come again.")